# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_a5r_wrappers", use_symbols = TRUE, package_name = "a5r")

#' @usage NULL
#' @useDynLib a5r, .registration = TRUE
NULL

#' Convert latitude/longitude to A5 cell ID
#' @param lon longitude in decimal degrees.
#' @param lat latitude in decimal degrees.
#' @param resolution resolution level of the grid
#' @export
lon_lat_to_cell <- function(lon, lat, resolution) .Call(wrap__lon_lat_to_cell, lon, lat, resolution)

#' Convert A5 cell ID to latitude/longitude
#' @param cell_id ID of the cell.
#' @export
cell_to_lon_lat <- function(cell_id) .Call(wrap__cell_to_lon_lat, cell_id)

#' Convert hexadecimal string to A5 cell ID
#' @param hex hexadecimal string representation of the cell ID.
#' @return A5 cell ID as a numeric value.
#' @export
hex_to_u64 <- function(hex) .Call(wrap__hex_to_u64, hex)

#' Convert A5 cell ID to hexadecimal string
#' @param cell_id ID of the cell.
#' @return hexadecimal string representation of the cell ID.
#' @export
u64_to_hex <- function(cell_id) .Call(wrap__u64_to_hex, cell_id)

#' Get the resolution of an A5 cell
#' @param cell_id ID of the cell.
#' @return resolution level (0-30) of the cell.
#' @export
get_resolution <- function(cell_id) .Call(wrap__get_resolution, cell_id)


# nolint end
