# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_a5r_wrappers", use_symbols = TRUE, package_name = "a5r")

#' @usage NULL
#' @useDynLib a5r, .registration = TRUE
NULL

#' Convert latitude/longitude to A5 cell ID
#' @param lon longitude in decimal degrees.
#' @param lat latitude in decimal degrees.
#' @param resolution resolution level of the grid
#' @export
lon_lat_to_cell <- function(lon, lat, resolution) .Call(wrap__lon_lat_to_cell, lon, lat, resolution)


# nolint end
